In [11]:
import numpy as np
import matplotlib.pyplot as plt

# 定数の設定
K = 0.47  # 熱伝導率 [W/mK]
rho = 1573  # 密度 [kg/m³]
cp = 967  # 比熱 [J/kgK]
alpha = K / (rho * cp)  # 熱拡散率
print(alpha)

h1 = 100  # 上の対流熱伝達係数 [W/m²K]
h2 = 50  # 下の対流熱伝達係数 [W/m²K]
T_ext1 = 50  # 上の外部温度 [K]（例）
T_ext2 = 50  # 下の外部温度 [K]（例）

# グリッドの設定
x = np.linspace(0, 1, 100)[:, None]  # 空間グリッド
t = np.linspace(0, 3600, 720)[:, None]  # 時間グリッド

dx = x[1] - x[0]  # 空間ステップ
dt = t[1] - t[0]  # 時間ステップ

Nx = len(x)
Nt = len(t)

# 初期条件
u = np.zeros((Nt, Nx))  # 初期温度を0Kと仮定

# 境界条件の設定
u[:, 0] = T_ext1
u[:, -1] = T_ext2


print(u)
print(u.shape)

# 数値解法の実装（前進オイラー法と中央差分法）
for n in range(0, Nt - 1):
    for i in range(1, Nx - 1):
        u[n + 1, i] = u[n, i] + alpha * dt * (u[n, i - 1] - 2 * u[n, i] + u[n, i + 1]) / dx**2

    # 境界条件の適用
    # 左端の対流境界条件
    u[n + 1, 0] = (4 * u[n + 1, 1] - u[n + 1, 2] + 2 * dx * h1 / K * T_ext1) / (3 + 2 * dx * h1 / K)

    # 右端の対流境界条件
    u[n + 1, -1] = (4 * u[n + 1, -2] - u[n + 1, -3] + 2 * dx * h2 / K * T_ext2) / (3 + 2 * dx * h2 / K)
    print(u[n + 1, 0], u[n + 1, 1], u[n + 1, 2], u[n + 1, -3], u[n + 1, -2], u[n + 1, -1])

# # 結果のプロット
# plt.imshow(u, extent=[0, 0.02, 0, 1200], aspect='auto', origin='lower', cmap='hot')
# plt.colorbar(label='Temperature [K]')
# plt.xlabel('Position [m]')
# plt.ylabel('Time [s]')
# plt.title('1D Heat Conduction with Convection Boundary Conditions')
# plt.show()

3.089887455780095e-07
[[50.  0.  0. ...  0.  0. 50.]
 [50.  0.  0. ...  0.  0. 50.]
 [50.  0.  0. ...  0.  0. 50.]
 ...
 [50.  0.  0. ...  0.  0. 50.]
 [50.  0.  0. ...  0.  0. 50.]
 [50.  0.  0. ...  0.  0. 50.]]
(720, 100)
29.86279741382546 0.7581526636631609 0.0 0.0 0.7581526636631609 21.45793803481359
30.096794517441154 1.1879720332808816 0.01149590922839092 0.01149590922839092 1.0605287027626384 21.690599346808238
30.324842559989847 1.6084790785317833 0.02916056628806637 0.027228136278096157 1.3574370228357255 21.91819046499923
30.547142764286626 2.01995953707892 0.05266833692314393 0.046987945927200944 1.6490307944062392 22.14087091419048
30.763888439922717 2.4226885948172274 0.0817091329040941 0.0705761494641899 1.9354577967521822 22.3587941771232
30.97526532433283 2.8169313216041574 0.11598766573779642 0.09780265894036491 2.216860634539364 22.57210794932999
31.181451908239826 3.2029430876318874 0.15522273696294625 0.1284860628659109 2.4933769449908416 22.780954382472327
31.3826

/var/folders/st/n5b89ytn4b98348x0tqzx3bh0000gn/T/ipykernel_69075/4062342006.py:40: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  u[n + 1, i] = u[n, i] + alpha * dt * (u[n, i - 1] - 2 * u[n, i] + u[n, i + 1]) / dx**2
/var/folders/st/n5b89ytn4b98348x0tqzx3bh0000gn/T/ipykernel_69075/4062342006.py:44: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  u[n + 1, 0] = (4 * u[n + 1, 1] - u[n + 1, 2] + 2 * dx * h1 / K * T_ext1) / (3 + 2 * dx * h1 / K)
/var/folders/st/n5b89ytn4b98348x0tqzx3bh0000gn/T/ipykernel_69075/4062342006.py:47: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you 